name: Django CI

on:
  push:
    branches: [ develop ]
  pull_requests:
    branches: [ main ]
jobs:
  
  build:
    env:
      GH_REPOS_SECRET_KEY : ${{ secrets.GH_REPOS_SECRET_KEY }}
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install poetry
        poetry install
    - name: Run Linter
      run: |
        make lint
    - name: Run Tests
      run: |
        poetry run python -m pytest
    - name: Make Test Coverage
      run: |
        make coverage.xml
